source 'https://github.com/malai520/TJRepo'
source 'https://github.com/CocoaPods/Specs.git'

target 'TJTestSubspecExcample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
#   --use-libraries

  # Pods for TJTestSubspecExcample


    pod 'TJTestSubspec/lib' , '~> 0.0.2'

end
